language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev" # 3.6 development branch
    - "nightly" # currently points to 3.7-dev
install:
    - pip install .
    - pip install -r requirements/docs.txt
    - pip install -r requirements/test.txt
script:
    - pytest --cov=./ pycondor
    - flake8 pycondor
    - bash ci/build_docs.sh
after_success:
    - pip install codecov
    - coverage combine
    - codecov
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        python: "2.7"
