sudo: required
language: python
services:
    - docker
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - docker build --build-arg PYTHON_VERSION=$TRAVIS_PYTHON_VERSION -t pycondor .

script:
    - docker run \
    -v $PWD/docs:/home/mapper/pycondor/docs pycondor \
    bash -e -c "pytest --cov=pycondor pycondor ;
                flake8 pycondor ;
                bash ci/build_docs.sh;
                codecov -t dfae3f20-4728-4219-a671-4d9b421bb176"

after_success:
    - pip install codecov
    - codecov

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        python: "3.6"
